[package]
name = "rust-hacks"
version = "0.1.0"
edition = "2021"
description = "Crust of Rust implementations"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
